开启效果:
  格挡: true
  盾反: true
  斧连击加成: true
  剑连击加成: true
  弓连击加成: true
time: 2000
cooldown: 3000
减免倍率: 0.1
反击伤害倍率: 10
伤害名称: "物理伤害"
三连反伤倍率: 0.5
剑附加伤害: 0.1
弓附加伤害: 0.1
怪物目前血量比例: 0.1
怪物已损失血量比例: 0.1
剑固定时间: true
成功提示: "&4触发成功"
失败提示: "&4触发失败"
触发指令:
  烈阳神锤:
    成功指令: "say %player% 测试1"
    失败指令: "say %player% 测试2"
  烈阳神锤2:
    成功指令: "say %player% 测试3"
    失败指令: "say %player% 测试4"


